# Docker Compose file with Redis integration for a server application.

services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      REDIS_URL: redis://redis:6379
    ports:
      - 8080:8080
    depends_on:
      - redis

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis-data:
